* 本文件用于记录对佛学的想法与笔记


、
** 宗性老司机
** 佛学感悟
生老病死，人生的终极苦难
人人无法逃离，快乐的短暂虚妄，痛苦的片刻难以忍受 众生平等
平等看待一切人，对他人保持怜悯心



闻思修 在生活中修行 吃饭 睡觉 学习上修行：
- [ ] 学习时，能否专心，无杂念
- [ ] 吃饭时，能否杜绝贪嗔痴
- [ ] 睡觉时，能否按时睡觉，不玩手机
- [ ] 对人上能否保持超然的心态，平等看待一切人，对旁人是否有怜悯心
- [ ] 对事上是否能保持超然心态，办事赶紧利落，不要犹豫不决，不要敷衍了事


** 唯识

** 禅修
- 降龙伏虎 用呼吸将意念拴住
- [ ] 数息时不要太用心
- [ ] 发觉妄想了就从头再来 
** 反省（用于反省平日）
*** <2018-08-13 周一>
- 昨日看小说1点才睡，严重影响学习规划，烦了我执的毛病（忏悔忏悔）
  

* 六度：布施，持戒，忍辱，精进，禅定，般若

** 1.施度（檀波罗蜜或檀那波罗蜜）：
有财施、法施和无畏施三种。谓菩萨由修布施，能对治悭吝贪爱烦恼，能施与众生利乐。看见一切人生受苦，心生慈悲，以“人溺己溺，人饥己饥”精神，布施所能，使苦人得乐，迷者受益，布施分为三种：
1.财布施——布施以金钱、物品去帮助穷苦者，改善他们的生活，或出资捐款印刷各种善书，经典劝化度人，以改善众生的心性。
2.无畏施——凡对痛苦的人，用温暖爱心加以安慰，遇人困难，施于援手解难，使受苦受难者心中得到平安，没有恐怖感。如对寺庙佛堂等，献出劳力清扫维护；或对毁谤正法者，能以无畏精神伸张真理感化之。
3.法布施——以自己所学，领悟的佛法真理，向世人宣说，使众生同沾法雨，转迷成悟。
** 2.戒度（尸波罗蜜或尸罗波罗蜜）：
包括出家、在家、大乘、小乘一切戒法和善法，谓菩萨由修一切戒法和善法，能断身口意一切恶业。
持戒——严守戒律，始能塑出端庄法相，持戒才能使身口意清净，不犯恶业。当守五戒：不杀生、不偷盗、不邪淫、不妄语、不饮酒。其它奢华歌舞，令人目迷神乱，香烟等亦当禁戒，以维身心清静。
** 3.忍度（羼提波罗蜜）：
谓菩萨由修忍辱，能忍受一切有情骂辱击打及外界一切寒热饥渴等之大行，无论业障魔障，即能断除瞋恚烦恼。
忍辱——修道途中，阻碍必多，遇挫折毁谤，不怨不怒，由忍化恕，心自安之，外忍饥寒，内忍七情六欲，如此道志不馁，不畏困难，学道度人必能成之。
** 4.精进度（毗梨耶波罗蜜）：
谓菩萨精励身心，精修一切大行，能对治懈怠，成就一切善法。
精进——佛海无边，道海高远，学无止境，真理研习不可停顿。若有过失，遇人指点，立即改正；凡对众生有利益工作，当仁不让，尽力去做，精进不怠，彼岸自达。
** 5.禅度（禅波罗蜜、禅度波罗蜜或禅那波罗蜜）：
止观双运名禅，亦名静虑、三昧、三摩地、定。谓思维真理，定止散乱，心一境性，调伏眼耳等诸根，会趣寂静妙境。有四禅、八定及一切三昧等。
禅定——要修炼成佛，必需寂静其心，以免散乱。要普度众生，精神须有特别训练，所以禅定才能生智慧，遇事才能有定力。
** 6.慧度（般若波罗蜜）：
谓通达诸法体性本空之智。及断除烦恼证得真性之慧，能对治愚痴无知（无明）。
智慧——修行者之心性当具有最高的智慧。博览群经、远大学识、历练世故，可以辩才无碍，圆通万事，度化众生自然方便，修行者本身亦可避免堕落魔障之中。













