#+TITLE: 小说构思

* 凡人灭仙传
** 时代背景：架空
** 人物：地球穿越者 科研狗 不需要其他任何金手指
** 开局：世家公子 旁支 
** 原则：前期科学修真 后期科研修真
   通过录音机来偷师最好功法
   通过统计来提高筑基率
   通过详细布置来狩猎
   通过生态圈进行前期积累
   通过数学来学习阵法

   通过统计数据来杀敌

   生物上通过杂交优化等方法来培育灵草灵药，神奇作物的退化与反古
   通过实验来推导功法（有点不人道）
   通过凡人驾驶机甲来推翻腐朽的统治
   通过电话来操纵物价大量积累财富，进行贸易战争

** 男女经历：有过刻骨铭心的爱情，但最终反映过来一切都是梦幻泡影
** 现在思路
尘凡出生
幼时聪颖过人，得知有修仙的存在想方设法，在经商上指点父母，使得家里财富增加
同时主动学习这个时代的知识，文字演变等
王朝与宗门的关系（供养关系）
十岁时，通过查找各地县志，而寻得玄铁，而供奉给驻守修士，跟其学得修真界常识
在选拔中成功入选，加入一个中等宗门
因为驻守修士的关照，提前选好导师，通过小手段成功进入最有前景的分部，因阵法而耽误的天才那（筑基后期）当徒弟
然后因为扎实的数学修养，而提前获得导师的好感，成功进入核心研发中，阵法方面得以成功入门，而修行方面也由于有筑基后期大修士进行指导也基础扎实，算得上稳扎稳打
进而进入练气期，灵根为  2 灵根，木土相生，低于变异灵根与单灵根（这种虽然不多，但每年都有  4 到5个），
功法方面：功法必须是一次次讲解，一次次答疑，而不应该是直接照着一本书死练
        通过阵法师助手的身份在讲法堂留下小后门，从而习得众多功法，然后进行分析得出，测试众多功法，但因数据不足，不敢随意创造功法，最终选了本门最牛逼的功法
        一般只有掌门候选人与宗门候选人才能修行 
然后就是每天非常充实的科研生活，跟着导师学习当前世界最顶尖的阵法知识，学习修真界的各种理论，跟着导师参加阵法师的交流协会，反正掌握了所有到金丹时期的阵法知识
然后师傅老死，死前语重心长的的一番话，over 退场
炼气期  9级（35岁），等级死活提不上去，回家一次，与一个美人结婚（为了留下后代），生活五年最终假死，正式舍弃尘缘，从此念头通达，瓶颈略有松动。在此期间创建免费书院，请各个行业最牛逼的凡人教学，只要通过考试就可以免费上课，收集了大量天才少年。
但是由于作物的灭亡，现代只能用不完整的筑基丹，会有瑕疵。
（在这  5 年期间秘密组织帮派，然后用死囚进行人体试验），最终培育出安全并且产量高的作物，可用于究竟筑基丹的炼制
在此期间遇到一个大派女神级人物，非常有炼丹师天赋，由于返古草药与其结缘，谈了一段轰轰烈烈的恋爱，并在上垒那天成功完美筑基，最终因为三观不合分手。在结婚当天，一场烟花告别。
然后开始下一场征途
后来有感于一个人在修仙界对资源收集的不够给力，与修仙界的麻木不仁，决定创建门派，然后向门派管理机构申请，看在逝去师傅的面子上，在完成了一个任务后开始创建了自己的门派，踏上掌门路。（40岁）。 
中途经理几次经历，最终成功结丹。 







* 








